# Generated by Django 3.1 on 2020-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemodel',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='office/img'),
        ),
    ]
